create table category (id integer not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table product (id integer not null auto_increment, description varchar(255), image varchar(255), price double precision not null, title varchar(255), primary key (id)) engine=InnoDB;
create table product_category (product_id integer not null, category_id integer not null, primary key (product_id, category_id)) engine=InnoDB;
alter table product_category add constraint FKkud35ls1d40wpjb5htpp14q4e foreign key (category_id) references category (id);
alter table product_category add constraint FK2k3smhbruedlcrvu6clued06x foreign key (product_id) references product (id);
INSERT INTO product(title, description, image, price) VALUES ('Nidio T-Shirt', 'Eu falei espaço?', 'https://uploaddeimagens.com.br/images/004/031/244/full/masc_white_nidio_espaco.png?1663809884', 25);
INSERT INTO product(title, description, image, price) VALUES ('We Need U T-Shirt', 'Casual White Nidio T-shirt', 'https://uploaddeimagens.com.br/images/004/032/233/original/masc_white_save_dolfini.jpg?1663870760', 25);
INSERT INTO product(title, description, image, price) VALUES ('Bootstrap Bill Turner T-shirt', 'Casual Bootstrap T-shirt', 'https://uploaddeimagens.com.br/images/004/032/240/original/fem_black_bootstrapBill.jpg?1663870910', 25);
INSERT INTO product(title, description, image, price) VALUES ('We Need U T-Shirt', 'Casual Dark Blue Nidio T-shirt', 'https://uploaddeimagens.com.br/images/004/032/242/full/masc_blue_save_dolfini.jpg?1663870987', 30);
INSERT INTO product(title, description, image, price) VALUES ('Marcelo`s Surf T-Shirt ', 'What about surfing and coding in Java?' , 'https://uploaddeimagens.com.br/images/004/032/245/full/masc_grey_marcelo_surf.jpg?1663871093', 50);
INSERT INTO product(title, description, image, price) VALUES ('Willian`s Mysterious T-Shirt', 'Warning! Reactive T-shirt' , 'https://uploaddeimagens.com.br/images/004/032/251/full/masc_marine_blue_wilian.jpg?1663871245', 65);
INSERT INTO product(title, description, image, price) VALUES ('Hokage Cristh Mug', 'The chosen one!', 'https://uploaddeimagens.com.br/images/004/040/680/full/hokagecristh.jpg?1664390608', 50);
INSERT INTO product(title, description, image, price) VALUES ('Cristh the Redeemer', 'A holy mug ', 'https://cdn.discordapp.com/attachments/1012420525039030332/1024388808373981194/caneca_christh_redentor.jpg', 50);
INSERT INTO product(title, description, image, price) VALUES ('Que café gostosinnn Mug', 'Renan`s secret nickname', 'https://uploaddeimagens.com.br/images/004/040/679/full/mug.jpeg?1664390571', 50);
INSERT INTO category(name) VALUES ('T-shirt');
INSERT INTO category(name) VALUES ('Mug');
INSERT INTO product_category (product_id, category_id) VALUES (1,1);
INSERT INTO product_category (product_id, category_id) VALUES (2,1);
INSERT INTO product_category (product_id, category_id) VALUES (3,1);
INSERT INTO product_category (product_id, category_id) VALUES (4,1);
INSERT INTO product_category (product_id, category_id) VALUES (5,1);
INSERT INTO product_category (product_id, category_id) VALUES (6,1);
INSERT INTO product_category (product_id, category_id) VALUES (7,2);
INSERT INTO product_category (product_id, category_id) VALUES (8,2);
INSERT INTO product_category (product_id, category_id) VALUES (9,2);
